version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Carpetas necesarias para trabajar
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./templates:/var/www/html/templates
      - ./translations:/var/www/html/translations
      - ./public:/var/www/html/public
      - ./assets:/var/www/html/assets
      - ./bin:/var/www/html/bin
      - ./.env:/var/www/html/.env
      - ./migrations:/var/www/html/migrations

      # Archivos de Composer
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock

      # Caché y logs en volúmenes internos (más rápidos)
      - cache_data:/var/www/html/var/cache
      - log_data:/var/www/html/var/log
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: "mysql://symfony:secret@db:3306/proveedores_symfony?serverVersion=5.7&charset=utf8mb4"
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: proveedores_symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db-data:
  cache_data:
  log_data:
