server {
    listen 80;
    server_name _;

    # Apunta al directorio public/ de Symfony
    root /var/www/html/public;
    index index.php;

    # Primer chequeo: si existe fichero o directorio, lo sirve, si no, lo pasa a index.php
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Procesado de ficheros PHP
    location ~ \.php$ {
        # Este host “php” debe coincidir con el nombre de tu servicio PHP en docker-compose
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param HTTPS           $https if_not_empty;
    }

    # Opcional: denegar acceso a .git, var/, vendor/, etc.
    location ~ /\.(?:env|git) {
        deny all;
    }
}
